// Generic model optimizer + loader codegen.
//
//   npm run optimize -- <path/to/model.glb|.gltf> [Name]
//
// 1. Optimizes the model with gltf-transform (draco geometry, webp textures,
//    dedup, instancing) into public/models/<Name>.glb
// 2. Generates src/game/models/<Name>.ts with a cached async loader.
//
// [Name] is optional; defaults to the input file name in PascalCase.
import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { basename, dirname, extname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const frontDir = join(dirname(fileURLToPath(import.meta.url)), '..')

const [inputArg, nameArg] = process.argv.slice(2)
if (!inputArg) {
  console.error('Usage: npm run optimize -- <path/to/model.glb|.gltf> [Name]')
  console.error('Example: npm run optimize -- ../map-src/props/bench.glb Bench')
  process.exit(1)
}

const inputPath = resolve(process.cwd(), inputArg)
if (!existsSync(inputPath)) {
  console.error(`Input not found: ${inputPath}`)
  process.exit(1)
}
const ext = extname(inputPath).toLowerCase()
if (ext !== '.glb' && ext !== '.gltf') {
  console.error(`Expected a .glb or .gltf file, got: ${ext || '(no extension)'}`)
  process.exit(1)
}

function toPascalCase(value) {
  const cleaned = value.replace(/[^a-zA-Z0-9]+/g, ' ').trim()
  if (!cleaned) return 'Model'
  const pascal = cleaned
    .split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
  // Identifiers cannot start with a digit
  return /^\d/.test(pascal) ? `Model${pascal}` : pascal
}

const name = toPascalCase(nameArg ?? basename(inputPath, ext))
const outputGlb = join(frontDir, 'public', 'models', `${name}.glb`)
const outputTs = join(frontDir, 'src', 'game', 'models', `${name}.ts`)

mkdirSync(dirname(outputGlb), { recursive: true })
mkdirSync(dirname(outputTs), { recursive: true })

console.log(`Optimizing ${inputPath}\n        -> ${outputGlb}`)
const result = spawnSync(
  'npx',
  [
    '--yes',
    '@gltf-transform/cli',
    'optimize',
    inputPath,
    outputGlb,
    '--compress',
    'draco',
    '--texture-compress',
    'webp',
    '--texture-size',
    '1024',
  ],
  { stdio: 'inherit', shell: true },
)
if (result.status !== 0) {
  console.error('gltf-transform optimize failed')
  process.exit(result.status ?? 1)
}

const loaderSource = `// Generated by \`npm run optimize\` from ${basename(inputPath)}.
// Safe to edit or regenerate (regenerating overwrites this file).
import * as THREE from 'three'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js'

const MODEL_URL = '/models/${name}.glb'

let cachedTemplate: THREE.Group | null = null
let inflight: Promise<THREE.Group> | null = null

/**
 * Loads (once) and returns the shared ${name} template.
 * Add it directly to the scene for a single instance, or use
 * \`(await load${name}()).clone(true)\` for multiple instances.
 * For skinned/animated models, clone with three's SkeletonUtils instead.
 */
export function load${name}(): Promise<THREE.Group> {
  if (cachedTemplate) return Promise.resolve(cachedTemplate)
  if (inflight) return inflight
  inflight = new Promise<THREE.Group>((resolvePromise, rejectPromise) => {
    const dracoLoader = new DRACOLoader()
    dracoLoader.setDecoderPath('/draco-decoder/')
    const loader = new GLTFLoader()
    loader.setDRACOLoader(dracoLoader)
    loader.load(
      MODEL_URL,
      (gltf) => {
        cachedTemplate = gltf.scene
        resolvePromise(gltf.scene)
      },
      undefined,
      (error) => {
        inflight = null
        rejectPromise(error instanceof Error ? error : new Error(String(error)))
      },
    )
  })
  return inflight
}
`

writeFileSync(outputTs, loaderSource)
console.log(`\nDone.`)
console.log(`  Model:  public/models/${name}.glb`)
console.log(`  Loader: src/game/models/${name}.ts`)
console.log(`\nUsage:`)
console.log(`  import { load${name} } from '../game/models/${name}'`)
console.log(`  const model = await load${name}()`)
console.log(`  scene.add(model)`)
